### ISSUE TITLE
PSSMs scale is off

### ISSUE THREAD

**Issue by mcreixell** [meyer-lab/resistance-MS#233]
For some reason the scale of the PSSMs is off. The output should be a log odds ratio which is clearly not. The model `scores` and `bg_prob` look good to me and the code below too. Is it possible that the only thing missing is transforming to log10? @aarmey 

https://github.com/meyer-lab/resistance-MS/blob/22237fbb4af059742f6491b8efb610f9495e4dab/msresist/clustering.py#L81-L95

<img width="1348" alt="Screen Shot 2020-09-30 at 8 53 33 PM" src="https://user-images.githubusercontent.com/46428799/94763409-03797500-035f-11eb-9f93-8c5e9f78fa95.png">

**Comment by mcreixell** [comment]
I tried and doesn't look good enough yet. I think that the problem is that the foreground probability matrix (sum of scores) should be somehow normalized to be between 0 and 1 to be able to then divide by the background probabilities and take the log2. This is the code of biopython we've been using so far:

https://github.com/biopython/biopython/blob/05107f5cfd1f8d67dbc4d472268618f2b6d93bc2/Bio/motifs/matrix.py#L301-L336

**Comment by aarmey** [comment]
Yep. Normalizing it should be perfectly fine because the scale is arbitrary. I would take the log of both matrices, subtract the background from the foreground, and then adding or subtracting from the resulting matrix by some value is fine (because it's equivalent to normalizing the original one).

**Comment by mcreixell** [comment]
This is the result of subtracting the log-transformed background from the log-transformed foreground so adding or subtracting a value wouldn't scale the data correctly either I think. We want the data to look something like the second screenshot.

![Screen Shot 2020-10-01 at 4 44 37 PM](https://user-images.githubusercontent.com/46428799/94873920-66254c00-0405-11eb-9a1e-d8aa6f7b71b5.png)


![Screen Shot 2020-10-01 at 5 09 05 PM](https://user-images.githubusercontent.com/46428799/94875159-d1245200-0408-11eb-91a6-f75bc2765226.png)

**Comment by aarmey** [comment]
What function did you use to generate them before?

**Comment by mcreixell** [comment]
First create a position weight matrix that shows the probabilities of finding each residue in every position: 

`pwm = m.counts.normalize(pseudocounts=AAfreq)`

Then `pssm = pwm.log_odds()`

**Comment by aarmey** [comment]
Pretty sure the problem is missing a pseudo count to buffer against positions that don't show up at all. See section 14.4 here:

http://biopython.org/DIST/docs/tutorial/Tutorial.html

A starting point would be to add 1.0 to all positions before log-transforming. This could be larger or smaller, but should generally be small enough to represent the effect of having one or two peptides at that position. It reduces the contribution of positions being completely absent, which happens a lot in data that isn't infinitely large.

**Comment by aarmey** [comment]
So, when you passed in AAfreq as pseudo counts, it was adding those values to the counts it found at each position for each amino acid. You don't want to do that—it shouldn't be proportional to aa frequency—but do need some offset to buffer against aa's that are just missing due to the dataset size.

**Comment by mcreixell** [comment]
True, in their example they use the natural nucleotide frequency so I thought pseudocounts was used as some sort of background. I wonder if this may be why we were seeing the tryptophan depletion.

**Comment by aarmey** [comment]
Hmm... I guess using the background as the pseudo count would prevent spurious enrichment for rare positions... maybe that's ok.

In either case I don't *think* this would explain the W depletion, but we'll have to see what the new results look like.
